---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  coffeelint:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  scss-lint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.css"
  - "**.coffee"
exclude_paths: []
